### ISSUE TITLE
Local ip for OVS must be set

### ISSUE THREAD

**Issue by kashif74** [puppetlabs/puppetlabs-openstack#107]
HI
I am installing a multinode setup on RHEL6.5 with neutron server running on controller node and a seperate machine for other network services. It failed with this error
 Local ip for ovs agent must be set when tunneling is enabled at <MY_MODULE_PATH>/modules/neutron/manifests/agents/ml2/ovs.pp:107

I can see that neutron server in profile/neutron/server.pp is including openstack::common::ovs which in turn creating neutrons::agents::ml2::ovs 
I dont understand that why a controller server needs ovs agent ? Or may be I am getting it wrong.
Thanks

**Comment by cmurphy** [comment]
@kashif74 did @mrunkel answer your question?

**Comment by kashif74** [comment]
Sorry I missed the reply from @mrunkel . I have a working neutron based OpenStack system and it doesn't need a controller with IP in the data subnet. Can you please point me to any document which recommend this configuration?
Thanks

**Comment by mrunkel** [comment]
It's not an openstack requirement, but a requirement of the puppet module.   I didn't find any documentation, I just figured it out by digging through the module.

**Comment by kashif74** [comment]
Exactly, It is not requirement of OpenStack and puppet module is forcing controller node to have an interface which it doesn't need. 
I solved this problem by  directly setting 'openstack::neutron::neutron_tunneling: false' in hiera for controller node only. I think the correct solution is to move  "class { '::neutron::agents::ml2::ovs': "  out of openstack/manifests/common/ovs.pp and only use where it is required.

**Comment by cmurphy** [comment]
I'm in agreement now that the agent configuration should not be required to be on the neutron server node. We should set this up to be more configurable.
