### ISSUE TITLE
Juno Installation

### ISSUE THREAD

**Issue by sakibsyl** [puppetlabs/puppetlabs-openstack#144]
I tried to configure/install Juno on CentOS6.6 and 7 and I'm getting a lot of error. I'm not sure if these error are expected. Errors are below..

1. When I tried to configure controller server with CenOS7 I'm getting the following errors.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Error from DataBinding 'hiera' while looking up 'openstack::tempest_username_admin': syntax error on line 108, col 85: `openstack::neutron::service_plugins: ['router','firewall','lbaas','vpnaas','metering']' on node controller.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping ru

Here is my common.yaml  config for neutron. 
openstack::neutron::password: 'whi-rtuz'
openstack::neutron::shared_secret: 'by-sa-bo'
openstack::neutron::core_plugin: 'ml2'
openstack::neutron::service_plugins: ['router','firewall','lbaas','vpnaas','metering']

I've downloaded most updated modules and as per the puppet commits this bug has been fixed.
https://github.com/puppetlabs/puppetlabs-openstack/commits/stable/juno

**Comment by guessi** [comment]
Hi sakibsyl,
please try to add a "space" after comma, problem should fixed.
for more detail, please have a look at #147

**Comment by cmurphy** [comment]
Merged #147, thanks @guessi !

**Comment by guessi** [comment]
hi @cmurphy,
please consider to merge it back to stable/juno.

thanks :)

**Comment by cmurphy** [comment]
@guessi Done.
