### ISSUE TITLE
deploy openstack meet mysql installation failure

### ISSUE THREAD

**Issue by yongluo2013** [puppetlabs/puppetlabs-openstack#148]
I deploy openstack controller node with puppet module puppetlabs-openstack , and meet below error:

puppet agent --test --debug

Debug: Executing '/usr/bin/yum -d 0 -e 0 -y list mysql'
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y list mysql' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Mysql::Client::Install/Package[mysql_client]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y list mysql' returned 1: Error: No matching Packages to list
Debug: /Stage[main]/Glance::Notify::Rabbitmq/Glance_api_config[DEFAULT/kombu_ssl_keyfile]: Nothing to manage: no ensure and the resource doesn't exist
Debug: Executing '/usr/bin/systemctl is-active memcached'
Debug: Executing '/usr/bin/systemctl is-enabled memcached'

My environment is :
openstack :rdo-juno
os:centos 7
puppetlabs-openstack : 5.0.1
[root@puppet ~]# puppet module list --tree
/etc/puppet/modules
└─┬ puppetlabs-openstack (v5.0.1)
  ├─┬ stackforge-ceilometer (v5.0.0)
  │ ├── puppetlabs-inifile (v1.2.0)
  │ └─┬ stackforge-keystone (v5.0.0)
  │   ├─┬ puppetlabs-apache (v1.2.0)
  │   │ ├── puppetlabs-stdlib (v4.5.1)
  │   │ └── puppetlabs-concat (v1.1.2)
  │   └─┬ stackforge-openstacklib (v5.0.0)
  │     ├── aimonb-aviator (v0.5.1)
  │     ├── puppetlabs-mysql (v2.3.1)
  │     └─┬ puppetlabs-rabbitmq (v3.1.0)
  │       ├── puppetlabs-apt (v1.7.0)
  │       └─┬ garethr-erlang (v0.3.0)
  │         └── stahnma-epel (v1.0.2)
  ├─┬ stackforge-cinder (v5.0.0)
  │ └── dprince-qpid (v1.0.2)
  ├── stackforge-glance (v5.0.0)
  ├── stackforge-heat (v5.0.0)
  ├─┬ stackforge-horizon (v5.0.0)
  │ └─┬ saz-memcached (v2.6.0)
  │   └── puppetlabs-firewall (v1.3.0)
  ├─┬ stackforge-neutron (v5.0.0)
  │ ├─┬ stackforge-nova (v5.0.0)
  │ │ └── duritong-sysctl (v0.0.1)
  │ └── stackforge-vswitch (v1.0.0)
  ├─┬ stackforge-swift (v5.0.0)
  │ ├─┬ puppetlabs-rsync (v0.4.0)
  │ │ └── puppetlabs-xinetd (v1.4.0)
  │ └── saz-ssh (v1.4.0)
  ├─┬ stackforge-tempest (v5.0.0)
  │ └── puppetlabs-vcsrepo (v1.2.0)
  ├── puppetlabs-mongodb (v0.10.0)
  └── puppetlabs-ntp (v3.3.0)
i have try it with this way:

try install mysql with yum manually ,it's success but run puppet still failure.

yum install mariadb mariadb-server MySQL-python

any else i missed?

For details logs and ,please see attached file. Thanks a lot!

**Comment by yongluo2013** [comment]
It looks like the mysql module added mariadb support for CentOS, Scientific Linux, and Oracle Linux in 3.0.0. The puppetlabs-openstack module as well as the stackforge modules are pinning to <3.0.0 in the metadata.json. we should change this to <4.0.0. In the mean time, if you manually upgrade your mysql module to the newest version it should work.

**Comment by fivesix** [comment]
I also meet this problem with juno,  I need to upgrade the mysql module to solve it but with some warning also:
puppet module upgrade --force puppetlabs-mysql

**Comment by cmurphy** [comment]
Thanks for reporting this. I've submitted a patch to the stackforge openstacklib module to bump the mysql version. Once that is merged we can bump the mysql version in the metadata here (or maybe just take it out, since it's redundant). In the mean time, upgrading manually is the only workaround.

**Comment by cmurphy** [comment]
The openstacklib patch has been merged, will remove the mysql dependency from here on the next major release.

**Comment by ksingh7** [comment]
@fivesix  Thanks ``` puppet module upgrade --force puppetlabs-mysql ``` fixed the problem for me as well. 
Env Juno , CentOS

**Comment by samehmohamed88** [comment]
+1 @fivesix
