### ISSUE TITLE
About HA

### ISSUE THREAD

**Issue by jiasir** [puppetlabs/puppetlabs-openstack#156]
Whether can deploy a highly available environment when I using this module?

**Comment by cmurphy** [comment]
This module isn't capable of deploying an HA setup yet. We're working on getting pacemaker capabilities in https://github.com/stackforge/puppet-openstack_extras and we'll be able to use that in this module eventually.

I'll add a note about that to the documentation.

**Comment by jiasir** [comment]
@cmurphy I want to deploy a HA OpenStack environment with version Juno. Can you recommend a way? Many thanks!

**Comment by benh57** [comment]
Also interested in this.

I modified a previous version of the module to use non neutron, nova-network distributed (HA) mode. 

Hoping to use Neutron DVR, if possible. Not as worried about other components being HA.

**Comment by cmurphy** [comment]
I don't have a good solution using puppet yet. I'd recommend reading the guide at http://docs.openstack.org/high-availability-guide/content/ch-intro.html and keeping an eye on the openstack_extras repository. Also join #openstack-operators and #puppet-openstack on freenode and talk to the folks there about their HA solutions.

**Comment by yongluo2013** [comment]
Also interested in this.

**Comment by Quentin-M** [comment]
I am currently deploying OpenStack HA using Puppet. Pacemaker is far from behind useful. Almost everything (everything except Ceilometer it seems) can become HA Active/Active using HAProxy, MySQL Galera and RabbitMQ HA Cluster. Even Neutron is HA with the new l3_ha feature.

**Comment by jiasir** [comment]
Thanks @cmurphy 
What modules did you use?  @Quentin-M 
I have a plan to using python and depend on ansible to auto deploy a HA environment. Are you interested in this? @yongluo2013 @benh57 @Quentin-M @cmurphy

**Comment by jiasir** [comment]
@Quentin-M Thanks! Can you share your module?

**Comment by Quentin-M** [comment]
Absolutely. You can find it there : https://github.com/Quentin-M/puppet-iaas
Feel free to do everything you want.

My puppet module is currently used to deploy a 25-nodes OpenStack infrastructure (commodity servers).

**Comment by jiasir** [comment]
@Quentin-M Thanks! I will try it:)

**Comment by cmurphy** [comment]
This limitation is documented in the README of this module: https://github.com/puppetlabs/puppetlabs-openstack/blame/5.0.0/README.md#L185

I've created https://tickets.puppetlabs.com/browse/OS-254 to put work for adding this in our backlog, but I do not expect it to be completed soon. Closing this for now.
