### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by 24chinmay** [puppetlabs/puppetlabs-openstack#157]
hi,
i request you to help me ,I need the puppet files which would install openstack juno to ubuntu 14.0.4.
Iam new to everything please guide me.

**Comment by cmurphy** [comment]
With regard to your first comment, The module is contained in this git repository. If you're unclear how to obtain them, I recommend getting up to speed on git before trying to attempt an openstack installation: http://git-scm.com/book/en/v2

With regard to your second comment, there is nothing in this repository that refers to the puppet-editfile module, so I'm afraid there's nothing I can do.
