### ISSUE TITLE
How to add multiple storage servers

### ISSUE THREAD

**Issue by sakibsyl** [puppetlabs/puppetlabs-openstack#163]
I'm trying to add multiple storage servers and I'm getting below error . 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: invalid address at /etc/puppet/modules/openstack/manifests/profile/cinder/volume.pp:4 on node cinder2.themicro.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Line number 4.
 4   $management_address = ip_for_network($management_network)

Here is my fixed ip's for storage server. Is it possible to add multiple ip's in common.yaml file.
openstack::storage::address::api: '192.168.1.154'
openstack::storage::address::management: '200.200.200.154'

**Comment by cmurphy** [comment]
No, it's not currently possible to add multiple IPs for storage servers. That would require an HA solution which we have not implemented yet.
