### ISSUE TITLE
About deployment

### ISSUE THREAD

**Issue by jiasir** [puppetlabs/puppetlabs-openstack#164]
I have a question to how to config the module's configuration.
1 step, I install the module using the flowing command: 
```puppet module install puppetlabs-openstack```
2 setp, I edit the configuration file to deploy multi-node:
```vi examples/common.yaml```
3 setp, Deploy a controller node just like this:
```
node 'control.localdomain' {
  include ::openstack::role::controller
} 
```
Do it right? Also need other Settings?

**Comment by cmurphy** [comment]
You need to make sure hiera is set up correctly on your puppetmaster and that you copy your edited common.yaml into the hiera data directory. You will also need to include the other roles, such as compute, network, and storage, on your other nodes. You will then run puppet first on the controller node and then on your other nodes.

**Comment by jiasir** [comment]
Thanks @cmurphy
