### ISSUE TITLE
Neutron Server Migration

### ISSUE THREAD

**Issue by sakibsyl** [puppetlabs/puppetlabs-openstack#174]
I'm running into an issue where I need to replace my existing neutron server with a new server and I'm not sure how to do that and I couldn't find any solution by googling. I will appreciate if you share your thoughts. 

I'm using icehouse and CentOS6.5.

My thoughts is run this "::openstack::role::network" on new server with a different IP [eth0, 1 ] and then swipe IP's with existing server and rerun puppet client but I'm not sure how to backup and restart ovs stuff.  

[root@abc123 network-scripts]# ovs-vsctl show
a23e5f6d-fd2a-4458-a642-be415c421354
    Bridge br-tun
        Port br-tun
            Interface br-tun
                type: internal
        Port "gre-0a500981"
            Interface "gre-0a500981"
                type: gre
                options: {in_key=flow, local_ip="192.169.1.25", out_key=flow, remote_ip="172.16.5.10"}

**Comment by cmurphy** [comment]
We can't really provide advice here. I would consult:

The operators guide: http://docs.openstack.org/openstack-ops/content/upgrade-icehouse-juno.html
The operators mailing list: http://lists.openstack.org/cgi-bin/mailman/listinfo/openstack-operators
The operators IRC channel, #openstack-operators
