### ISSUE TITLE
Icehouse to Juno upgrade

### ISSUE THREAD

**Issue by sakibsyl** [puppetlabs/puppetlabs-openstack#189]
We are using Icehouse in out staging environment with CentOS 6.5. (One Controller, One Network, One Storage and couple of Compute nodes)

Now we are planning to upgrade out staging environment  to Juno. 

Is it possible to do the upgrade without upgrading Operating System ( CentOS 6 to 7) using puppetlabs-openstack modules ?

I found below link but I'm not sure the right procedure for the upgrade since we were using puppet modules.
 
http://docs.openstack.org/openstack-ops/content/upgrade-icehouse-juno.html

**Comment by benh57** [comment]
No. Even without using the puppet modules, RDO only has packaged RPMs for Juno for 7+, and this module depends on them, ie:

https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/
vs 
https://repos.fedorapeople.org/repos/openstack/openstack-juno/

(this also delayed our upgrade to Juno - wish they had made centos 6 RPMs, but there are very nice KVM improvments in 7+, so it will be for the best...)

**Comment by cmurphy** [comment]
Thanks @benh57.

This module depends on the distro packages, so it isn't possible to upgrade using this module.

We removed RedHat 6 from the metadata.json in #190 to clarify that. Thanks.
