### ISSUE TITLE
puppet master and agent configuration - openstack

### ISSUE THREAD

**Issue by cooldharma06** [puppetlabs/puppetlabs-openstack#214]
I am testing the puppet-openstack in my machine.

In which ip puppet master and agents are running (configured).

i checked puppet.conf no related configuration is mentioned but how it got synced.

Please clarify my doubt or tell some suggestions to find this one.

**Comment by cmurphy** [comment]
Your puppet master and puppet agents can have any IP addresses as long as the agents can connect to the master. For help configuring your puppet master and puppet agents please check the resources at [puppet's getting help guide](https://puppetlabs.com/community/get-help).
