### ISSUE TITLE
exited with 128: fatal: No such remote 'cache'

### ISSUE THREAD

**Issue by nati** [puppetlabs/puppetlabs-openstack#84]
Hi 

I got this error when I try multinode example with vmware fusion + vagrand.
Can we ignore this one?

[R10K::TaskRunner - ERROR] Task #R10K::Task::Module::Sync:0x007ff7d2150960 failed while running: Command git --git-dir /Users/nueno/work/puppetlabs-openstack/examples/multinode/modules/apt/.git --work-tree /Users/nueno/work/puppetlabs-openstack/examples/multinode/modules/apt remote set-url cache /Users/nueno/.r10k/git/git---github.com-puppetlabs-puppetlabs-apt exited with 128: fatal: No such remote 'cache'

**Comment by reecemarkowsky** [comment]
can you expand upon what you mean by 'cleared out the old environments' @jefforulez
