### ISSUE TITLE
how to define a rabbit host different from the controller or a different rabbit port ?

### ISSUE THREAD

**Issue by aleita** [puppetlabs/puppetlabs-openstack#93]
Hi,

in openstack::common:nova rabbit_hosts is defined in way that seems difficult to really manage, for instance I would like to define a different port from the default one as well as is not possible to define a rabbit server different from the controller.

**Comment by cmurphy** [comment]
I believe this was addressed in https://github.com/puppetlabs/puppetlabs-openstack/pull/125

Thanks!
