### ISSUE TITLE
Neutron exec resource error

### ISSUE THREAD

**Issue by hundredacres** [puppetlabs/puppetlabs-openstack#99]
When using the multimode example, I'm getting the following error -

Error 400 on SERVER: Could not find resource 'Exec[neutron-db-sync]' for relationship from 'Class[Neutron::Db::Mysql]' on node ....

I've updated the info from common.yaml to be environment specific and am trying to initialize the controller node before I move on to the other nodes.

**Comment by cmurphy** [comment]
@hundredacres any chance you have a configuration issue similar to @thomas-p-wilson's?

**Comment by cmurphy** [comment]
This would happen if $is_controller is undefined here: https://github.com/puppetlabs/puppetlabs-openstack/blob/master/manifests/common/neutron.pp#L47

This would occur if you had misconfigured the addresses in your hiera data. Please check that you've configured your API addresses correctly and re-open this issue if you think there is a larger problem.

**Comment by cappetta** [comment]
@cmurphy - I've been navigating through a packstack install and I'm seeing the same issue here.  at this point I don't believe its a self-induced issue as I've confirmed the addresses are correct in the hiera file and I've specifically initialized the is_controller variable in the init.pp 

After I did all that the error is still present.  I'll continue debugging and tracing the issue through the system but I'm currently trying to understand where neutron-db-sync is called and I'm seeing it in neutron::db::sync not in neutron::db:mysql.  

```
bash-4.2$ grep -r "neutron-db-sync" ./puppet/
./puppet/modules/openstack/manifests/profile/neutron/server.pp:  Class['::neutron::db::mysql'] -> Exec['neutron-db-sync']
./puppet/modules/neutron/manifests/db/mysql.pp:  ::Openstacklib::Db::Mysql['neutron'] ~> Exec <| title == 'neutron-db-sync' |>
./puppet/modules/neutron/manifests/db/postgresql.pp:  ::Openstacklib::Db::Postgresql['neutron'] ~> Exec <| title == 'neutron-db-sync' |>
./puppet/modules/neutron/manifests/db/sync.pp:  Package<| tag == 'neutron-package' |> ~> Exec['neutron-db-sync']
./puppet/modules/neutron/manifests/db/sync.pp:  Exec['neutron-db-sync'] ~> Service <| tag == 'neutron-db-sync-service' |>
./puppet/modules/neutron/manifests/db/sync.pp:  Neutron_config<||> ~> Exec['neutron-db-sync']
./puppet/modules/neutron/manifests/db/sync.pp:  Neutron_config<| title == 'database/connection' |> ~> Exec['neutron-db-sync']
./puppet/modules/neutron/manifests/db/sync.pp:  exec { 'neutron-db-sync':
./puppet/modules/neutron/manifests/plugins/ml2.pp:  } Neutron_plugin_ml2<||> ~> Exec<| title == 'neutron-db-sync' |>
./puppet/modules/neutron/manifests/server.pp:    tag        => ['neutron-service', 'neutron-db-sync-service'],
./puppet/modules/neutron/spec/classes/neutron_db_sync_spec.rb:    it 'runs neutron-db-sync' do
./puppet/modules/neutron/spec/classes/neutron_db_sync_spec.rb:      is_expected.to contain_exec('neutron-db-sync').with(
./puppet/modules/neutron/spec/classes/neutron_server_spec.rb:        :tag     => ['neutron-service', 'neutron-db-sync-service'],
```
